---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 5-demo-helm-release-git-helm-bb-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-helm-bb-app
  interval: 1m0s
  targetNamespace: 5-demo
  values:
    fullnameOverride: ""
    image:
      pullPolicy: Always
      repository: siddharth67/block-buster-dev:7.5.0
      tag: ""
    imagePullSecrets: []
    labels:
      app:
        env: dev
        name: block-buster
        version: 7.5.0
    nameOverride: ""
    namespace:
      name: 5-demo
    replicaCount: 2
    service:
      nodePort: 30005
      port: 80
      targetPort: 80
      type: NodePort
