---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: 8-demo-image-update-block-buster
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdboot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: master
  interval: 1m40s
  sourceRef:
    kind: GitRepository
    name: simple-app-repo
  update:
    path: ./8-demo
    strategy: Setters
