apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pods
  name: pods
  namespace: default
spec:
  containers:
    image: nginx
    name: primeiro-flux
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
