---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: primeiro-flux
  name: primeiro-flux
  namespace: default
spec:
  containers:
  - image: nginx
    name: primeiro-flux
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
