apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pods
  name: pods
  namespace: default
spec:
  containers:
  - args:
    - primeiro-flux
    image: nginx
    name: pods
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
