---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: simple-app-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/jorgejsilva/sample-app-deployment.git
