---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: simple-app-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: 8-demo-git-bb-app-auth
  url: ssh://github.com/jorgejsilva/sample-app-deployment.git
